### ISSUE TITLE
about inference result

### ISSUE THREAD

**Issue by wanboyang** [YuanEZhou/CBTrans#1]
Thanks for this amazing work.
Could you provide the inference captions of COCO test set by using the method proposed in this paper.
It is hard to download the features used in this paper due to its large size.
Thanks again.

**Comment by YuanEZhou** [comment]
@wanboyang  OK， I will upload it later since our servers are shut down for maintenance.

**Comment by YuanEZhou** [comment]
Hi @wanboyang, you can download the test results of single model setting from [link1 ](https://mailhfuteducn-my.sharepoint.com/:u:/g/personal/ye_zhou_mail_hfut_edu_cn/EemW-GUE0iREtPzpAVccIMMB46hSmLMc7DwswNHEIB888w?e=lWTdzs)and [link2](https://mailhfuteducn-my.sharepoint.com/:u:/g/personal/ye_zhou_mail_hfut_edu_cn/ERv-qIfLK_9IjKjdU0iyb5UBxhH6a5LB14SHK0lAp-_2VQ?e=k0PgnT).

**Comment by wanboyang** [comment]
> Hi @wanboyang, you can download the test results of single model setting from [link1 ](https://mailhfuteducn-my.sharepoint.com/:u:/g/personal/ye_zhou_mail_hfut_edu_cn/EemW-GUE0iREtPzpAVccIMMB46hSmLMc7DwswNHEIB888w?e=lWTdzs)and [link2](https://mailhfuteducn-my.sharepoint.com/:u:/g/personal/ye_zhou_mail_hfut_edu_cn/ERv-qIfLK_9IjKjdU0iyb5UBxhH6a5LB14SHK0lAp-_2VQ?e=k0PgnT).

Thanks for timely replying.
